stages:
  - deploy

deploy_green:
  stage: deploy
  only:
    - web
  script:
   - chmod 755 extra/deploy.sh; extra/deploy.sh green
  tags:
   - mithril_stand_deployment
  when: manual

deploy_yellow:
  stage: deploy
  only:
    - web
  script:
   - chmod 755 extra/deploy.sh; extra/deploy.sh yellow
  tags:
   - mithril_stand_deployment
  when: manual
