stages:
  - deploy

deploy_green:
  stage: deploy
  only:
    - web
  script:
   - chmod 755 extra/deploy.sh; extra/deploy.sh green
  tags:
   - deploy_docs_PRD_N
  when: manual

deploy_yellow:
  stage: deploy
  only:
    - web
  script:
   - chmod 755 extra/deploy.sh; extra/deploy.sh yellow
  tags:
   - deploy_docs_PRD_N
  when: manual

deploy_magenta:
  stage: deploy
  only:
    - web
  script:
   - chmod 755 extra/deploy.sh; extra/deploy.sh magenta
  tags:
   - deploy_docs_PRD_N
  when: manual
